AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    # Allows an application running locally on port 8080 to call this API
    Cors:
      # AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'http://localhost:8080'" 

Metadata:
  AWS::ServerlessRepo::Application:
    Name: AWSWorkshopRuan
    Description: hello world
    Author: Ruan Beukes
    #SpdxLicenseId: Apache-2.0
    #LicenseUrl: LICENSE.txt
    #ReadmeUrl: README.md
    #Labels: ['tests']
    #HomePageUrl: https://github.com/user1/my-app-project
    #SemanticVersion: 0.0.1
    #SourceCodeUrl: https://github.com/user1/my-app-project

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  ItemsFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: items/
        Handler: app.lambdaHandler
        Runtime: nodejs10.x
        Events:
          Items:
            Type: Api 
            Properties:
              Path: /items
              Method: get
  ItemsByIdFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: item-by-id/
        Handler: app.lambdaHandler
        Runtime: nodejs10.x
        Events:
          ItemsById:
            Type: Api 
            Properties:
              Path: /items/id/{id}
              Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ItemsApi:
    Description: "API Gateway endpoint URL for Prod stage for Items API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items/"
  ItemsFunction:
    Description: "Items Lambda Function ARN"
    Value: !GetAtt ItemsFunction.Arn
  ItemsFunctionIamRole:
    Description: "Implicit IAM Role created for Items function"
    Value: !GetAtt ItemsFunctionRole.Arn
  ItemsByIdApi:
    Description: "API Gateway endpoint URL for Prod stage for Items by Id API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items/id/{id}"
  ItemsByIdFunction:
    Description: "Items by Id Lambda Function ARN"
    Value: !GetAtt ItemsFunction.Arn
  ItemsByIdFunctionIamRole:
    Description: "Implicit IAM Role created for Items by Id function"
    Value: !GetAtt ItemsFunctionRole.Arn
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
